# Generated by Django 5.2.11 on 2026-02-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_reg', '0002_department_alter_employee_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
